// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 15.1 (Build Build 189 12/02/2015)
// Created on Mon Jun 17 15:40:53 2019

Register_File Register_File_inst
(
	.Read_Reg_Num_1(Read_Reg_Num_1_sig) ,	// input [4:0] Read_Reg_Num_1_sig
	.Read_Reg_Num_2(Read_Reg_Num_2_sig) ,	// input [4:0] Read_Reg_Num_2_sig
	.Write_Reg_Num(Write_Reg_Num_sig) ,	// input [4:0] Write_Reg_Num_sig
	.Reg_Write(Reg_Write_sig) ,	// input  Reg_Write_sig
	.Clear(Clear_sig) ,	// input  Clear_sig
	.Clock(Clock_sig) ,	// input  Clock_sig
	.Write_Data(Write_Data_sig) ,	// input [31:0] Write_Data_sig
	.Read_Data1(Read_Data1_sig) ,	// output [31:0] Read_Data1_sig
	.Read_Data2(Read_Data2_sig) ,	// output [31:0] Read_Data2_sig
	.out(out_sig) 	// output [31:0] out_sig
);

